# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bf313c1981f6dc91e49af1c0ededac0"
name = "Dalt FAQs"
handle = "dalt-faqs"
application_url = "https://mason-pan-linux-mill.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chowk-ko-pasal.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mason-pan-linux-mill.trycloudflare.com/auth/callback",
  "https://mason-pan-linux-mill.trycloudflare.com/auth/shopify/callback",
  "https://mason-pan-linux-mill.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
